In [ ]:
#LOADING DATASET

import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
df=pd.read_csv("/content/archive (11).zip")
df

,name,ratings,price,imgURL,corpus
0,"REDMI Note 12 Pro 5G (Onyx Black, 128 GB)",4.2,23999,https://rukminim2.flixcart.com/image/312/312/x...,Storage128 GBRAM6 SystemAndroid 12Processor T...
1,"OPPO F11 Pro (Aurora Green, 128 GB)",4.5,"₹20,999",https://rukminim2.flixcart.com/image/312/312/k...,Storage128 GBRAM6 GBExpandable Storage256GB S...
2,"REDMI Note 11 (Starburst White, 64 GB)",4.2,13149,https://rukminim2.flixcart.com/image/312/312/x...,Storage64 GBRAM4 SystemAndroid 11Processor Sp...
3,"OnePlus Nord CE 5G (Blue Void, 256 GB)",4.1,21999,https://rukminim2.flixcart.com/image/312/312/x...,Storage256 GBRAM12 SystemAndroid Q 11Processo...
4,"APPLE iPhone 13 mini (Blue, 128 GB)",4.6,3537,https://rukminim2.flixcart.com/image/312/312/k...,Storage128 SystemiOS 15Processor TypeA15 Bion...
...,...,...,...,...,...
2541,"REDMI Note 9 (Shadow Black, 64 GB)",4.3,11999,https://rukminim2.flixcart.com/image/312/312/k...,Storage64 GBRAM4 GBExpandable Storage512GB Sy...
2542,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,30203,https://rukminim2.flixcart.com/image/312/312/x...,Storage128 GBRAM8 SystemAndroid 11Processor S...
2543,Motorola a50,4.1,1549,https://rukminim2.flixcart.com/image/312/312/k...,NaN
2544,"SAMSUNG Galaxy S22 Ultra 5G (Phantom Black, 25...",4.3,20463,https://rukminim2.flixcart.com/image/312/312/x...,Storage256 GBRAM12 SystemAndroid 12Processor ...
2545,"vivo T2x 5G (Aurora Gold, 128 GB)",4.4,13999,https://rukminim2.flixcart.com/image/312/312/x...,Storage128 GBRAM6 SystemAndroid 13Processor T...

In [ ]:
#INSERTING INDEX COLUMN
df.insert(0, 'Index', range(1, len(df) + 1))

In [ ]:
df.head()

,Index,name,ratings,price,imgURL,corpus
0,1,"REDMI Note 12 Pro 5G (Onyx Black, 128 GB)",4.2,23999,https://rukminim2.flixcart.com/image/312/312/x...,Storage128 GBRAM6 SystemAndroid 12Processor T...
1,2,"OPPO F11 Pro (Aurora Green, 128 GB)",4.5,"₹20,999",https://rukminim2.flixcart.com/image/312/312/k...,Storage128 GBRAM6 GBExpandable Storage256GB S...
2,3,"REDMI Note 11 (Starburst White, 64 GB)",4.2,13149,https://rukminim2.flixcart.com/image/312/312/x...,Storage64 GBRAM4 SystemAndroid 11Processor Sp...
3,4,"OnePlus Nord CE 5G (Blue Void, 256 GB)",4.1,21999,https://rukminim2.flixcart.com/image/312/312/x...,Storage256 GBRAM12 SystemAndroid Q 11Processo...
4,5,"APPLE iPhone 13 mini (Blue, 128 GB)",4.6,3537,https://rukminim2.flixcart.com/image/312/312/k...,Storage128 SystemiOS 15Processor TypeA15 Bion...

In [ ]:
#NO OF ROWS AND COLUMNS IN DATAFRAME

print("no of columns:",df.shape[1])
print("no of rows:",df.shape[0])

no of columns: 6
no of rows: 2546

In [ ]:
#CHECKING MISSING VALUE

df.isna().sum()

Index       0
name        0
ratings     0
price       0
imgURL      0
corpus     12
dtype: int64

In [ ]:
#CHECKING COLUMNS

df.columns

Index(['Index', 'name', 'ratings', 'price', 'imgURL', 'corpus'], dtype='object')

In [ ]:
#SELECTING RELEVENT FEATURES FOR RECOMMENDATION

selected_features=["name","price","corpus"]
print(selected_features)

['name', 'price', 'corpus']

In [ ]:
#REPLACING THE NULL VALUES WITH NULL STRINGS

for feature in selected_features:
  df[feature]=df[feature].fillna("")

In [ ]:
#COMBINING SELECTED FEATURES

combined_features=df["name"]+' '+df["price"]+' '+df["corpus"]
print(combined_features)

0       REDMI Note 12 Pro 5G (Onyx Black, 128 GB) 2399...
1       OPPO F11 Pro (Aurora Green, 128 GB) ₹20,999 St...
2       REDMI Note 11 (Starburst White, 64 GB) 13149 S...
3       OnePlus Nord CE 5G (Blue Void, 256 GB) 21999 S...
4       APPLE iPhone 13 mini (Blue, 128 GB) 3537 Stora...
                              ...
2541    REDMI Note 9 (Shadow Black, 64 GB) 11999 Stora...
2542    OnePlus 9 5G (Astral Black, 128 GB) 30203 Stor...
2543                                   Motorola a50 1549
2544    SAMSUNG Galaxy S22 Ultra 5G (Phantom Black, 25...
2545    vivo T2x 5G (Aurora Gold, 128 GB) 13999 Storag...
Length: 2546, dtype: object

In [ ]:
#CONVERTING TEXT DATA TO VECTORS
vectorizer=TfidfVectorizer()
feature_vectors= vectorizer.fit_transform(combined_features)
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 122581 stored elements and shape (2546, 3420)>
  Coords	Values
  (0, 2719)	0.10803963180498687
  (0, 2523)	0.12394903479465565
  (0, 135)	0.12601357990096204
  (0, 2667)	0.10343277208916112
  (0, 901)	0.14226104100473794
  (0, 2558)	0.21395730507831767
  (0, 1493)	0.08761488813447753
  (0, 166)	0.06808004425421743
  (0, 2072)	0.036394961159740134
  (0, 529)	0.19494213817147862
  (0, 3017)	0.06811486423469491
  (0, 2081)	0.0991871414330179
  (0, 3073)	0.04203603781850627
  (0, 194)	0.08998102126487968
  (0, 3208)	0.08761488813447753
  (0, 1742)	0.13282512504448585
  (0, 64)	0.22086992460399063
  (0, 2983)	0.05097412452850835
  (0, 854)	0.1753503636888002
  (0, 1220)	0.06698341312553369
  (0, 662)	0.06964528211844437
  (0, 347)	0.09747784869276716
  (0, 1614)	0.06661411448285955
  (0, 1747)	0.07154313296869591
  (0, 2937)	0.05578369449099545
  :	:
  (2545, 2983)	0.07338360013301176
  (2545, 854)	0.252438685139565
  (2545, 1220)	0.1928619294520461
  (2545, 662)	0.2005261132546722
  (2545, 1614)	0.0958993133406519
  (2545, 1747)	0.15449287390217303
  (2545, 2937)	0.08030757503603352
  (2545, 1661)	0.05149762463405769
  (2545, 2190)	0.051517847781763805
  (2545, 61)	0.094476773361865
  (2545, 2642)	0.07146756527282928
  (2545, 3183)	0.20094581142288298
  (2545, 2153)	0.1846491865801362
  (2545, 1458)	0.2903431903254388
  (2545, 2117)	0.18969726005931795
  (2545, 232)	0.1612283839592573
  (2545, 2797)	0.21568047888753478
  (2545, 2252)	0.13047423209015097
  (2545, 3082)	0.2695608462310686
  (2545, 3307)	0.1653453535577489
  (2545, 1025)	0.2137276496588101
  (2545, 3174)	0.22863288135086068
  (2545, 229)	0.2695608462310686
  (2545, 890)	0.238493011821121
  (2545, 915)	0.30801818504254996

In [ ]:
#GETTING SIMILARITY SCORES USING COSINE SIMILARITY
similarity=cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.09812724 0.12398447 ... 0.         0.06928165 0.22307799]
 [0.09812724 1.         0.01971056 ... 0.         0.0094316  0.09579978]
 [0.12398447 0.01971056 1.         ... 0.         0.01984445 0.09525992]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.06928165 0.0094316  0.01984445 ... 0.         1.         0.05767627]
 [0.22307799 0.09579978 0.09525992 ... 0.         0.05767627 1.        ]]

In [ ]:
print(similarity.shape)

(2546, 2546)

In [ ]:
#GETTING THE PHONE NAME FROM THE USER
mobile_name=input("enter your favourite phone name:")

In [ ]:
#CREATING A LIST WITH ALL THE MOBILE NAME GIVEN IN THE DATASET
list_of_all_name = df["name"].tolist()
print(list_of_all_name)

In [ ]:
#FINDING THE CLOSE MATCH MOBILE NAME GIVEN BY THE USER

find_close_match=difflib.get_close_matches(mobile_name,list_of_all_name)
print(find_close_match)

In [ ]:
close_match=find_close_match[0]
print(close_match)

In [ ]:
#FINDING THE INDEX OF THE MOBILE WITH NAME
index_of_the_mobile=df[df.name==close_match]["index"].values[0]
print(index_of_the_mobile)

In [ ]:
#GETTING A LIST OF SIMILIAR MOBILE
similarity_score=list(enumerate(similarity[index_of_the_mobile]))
print(similarity_score)

In [ ]:
len(similarity_score)

In [ ]:
#SORTING THE MOBILES BASED ON SIMILARITY SCORE
sorted_similar_mobiles=sorted(similarity_score, key=lambda x:x[1], reverse=True)
print(sorted_similar_mobiles)

In [ ]:
#PRINT SIMILAR MOBILES BASED ON THE INDEX
print("mobiles suggested for you: /n")
i=1
for mobile in sorted_similar_mobiles:
  index=mobiles[0]
  name_from_index=df[df.index==index]["title"].values[0]
  if (i<30):
    print(i,".",name_from_index)
    i+=1

In [ ]:
mobile_name=input("enter your your favourite mobile:")
list_of_all_name=df["name"].tolist()
find_close_match=difflib.get_close_matches(mobile_name,list_of_all_name)
close_match=find_close_match[0]
index_of_the_mobile=df[df.name==close_match]["index"].values[0]
similarity_score=list(enumerate(similarity[index_of_the_mobile]))
sorted_similar_mobiles=sorted(similarity_score, key=lambda x:x[1], reverse=True)
print("mobiles suggested for you: /n")
i=1
for mobile in sorted_similar_mobiles:
  index=mobile[0]
  name_from_index=df[df.index==index]["title"].values[0]
  if(i<10):
    print(i,".",name_from_index)
    i+=1